### ISSUE TITLE
After cloning the project, unable to run it on local server.

### ISSUE THREAD

**Issue by SANKARAMDAS** [mah51/mikeroph.one#29]
Hi there, after cloning the project unable to run it on local server. Can you please check it from your side and add the running process for the local server after cloning.
![2022-05-15 (14)](https://user-images.githubusercontent.com/31897843/168475688-564d38be-2e0e-4a05-a1b4-64534da084cd.png)

**Comment by mah51** [comment]
Hi Sankaramdas, I will not be able to have a look at this until tomorrow. You could try upgrading both packages to the latest in package.json. If that doesn't work ill get back to you in a bit

**Comment by SANKARAMDAS** [comment]
Hi @mah51, I solved the issue I'm facing during installation process. So you don't need to check your code for issues. Cheers to you for this wonderful project.

**Comment by mah51** [comment]
Great! sorry I couldnt help sooner. If you don't mind please can you write what you did to solve it incase anyone else has the same problem. Thanks!

**Comment by SANKARAMDAS** [comment]
Why not.  
Before running the project on local mechine, I upgrade my npm, then In the project update "next-plausible" package. And it's done.
